### ISSUE TITLE
Full of Bugs for every version of Python

### ISSUE THREAD

**Issue by fahdmirza** [sandesh-bharadwaj/BetterSearch#2]
Hi,
  An honest feedback. I have been trying to get this installed on windows 2022 server with a6000 GPU and this is the buggiest piece of software I have seen this year. I have tried installing it with python 3.9, 3.10, and 3.12 and there are numerous compatibility errors. For example, with python 3.10, here is one:

  numpy\core\src\multiarray\scalartypes.c.src(3913): warning C4244: 'return': conversion from 'npy_intp' to 'int', possible loss of data
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild\src.win-amd64-3.10\numpy\core\src\umath -Ibuild\src.win-amd64-3.10\numpy\core\src\npymath -Ibuild\src.win-amd64-3.10\numpy\core\src\common -Inumpy\core\include -Ibuild\src.win-

and there are many many more on every version of Python. 

My suggestion is that please don't put it online in this state. I have literally wasted around 5 hours on this and I am not exaggerating. Thanks.

**Comment by tensorsofthewall** [comment]
Hi, thanks for the feedback. As I mentioned in the README, this is an alpha version, so I've not had time/resources to do extensive testing, and I apologize for the inconvenience. I did set up fresh environments and test this on 2 different Windows 10/11 Home machines with different hardware configurations and it worked correctly on both. 

1. This could be due to using this on a Windows Server, I only have access to Windows 10/11 Home machines. I'm confident this would work on Pro machines as well, but I don't know about  Servers.
2. Did you try installing this in a conda/venv environment? 
3. Do you have older versions of numpy?

**Comment by fahdmirza** [comment]
Thanks Sandesh for the reply. I am sorry if I sounded bit off but I liked the tool and still believe its great idea and really wanted it to work. 

This could be due to using this on a Windows Server, I only have access to Windows 10/11 Home machines. I'm confident this would work on Pro machines as well, but I don't know about Servers.
Yes I am using windows server 2022 as where I have GPU card. 
-- Did you try installing this in a conda/venv environment?
yes also tried it with conda and same result. 
-- Do you have older versions of numpy?
No, latest version 

Thanks.

**Comment by tensorsofthewall** [comment]
I just pushed a commit (c3f17d86651f6612995595237047c6bf360e5039) that provides a .yml file for building a conda environment. Can you see if that fixes things? If not, this may be an issue particularly for Windows Server.

**Comment by fahdmirza** [comment]
Hi Mate, tried but same issue. I think may be server is not supported or something, not sure. Do you have plan to release it for Ubuntu?

**Comment by tensorsofthewall** [comment]
Yes, I plan to release it for Linux and MacOS eventually.
